config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
    resources :brothers, only: [:index, :new, :create]
    
    get '/brother/:id', to: 'brothers#show', as: 'brother'
    
    get '/', to: 'brothers#index'
    get '/home', to: 'brothers#index' 
    #used in admin view to link back to home page 
    get 'list', to: 'brothers#list'
    get 'admin', to: 'brothers#admin'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brother.rb
class Brother < ActiveRecord::Base
   def to_s
      self.first_name + " " + self.last_name 
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brothers_controller.rb
class BrothersController < ApplicationController
# Integrate a controller action in the brothers' controller for handling the index action
    def index
        @brothers = Brother.all
    end
    
    def home
        @brothers = Brother.all
    end
    
    def create
        Brother.create(first_name: params[:brother][:first_name], last_name: params[:brother][:last_name], on_time: params[:brother][:on_time], email: params[:brother][:email])
        
        redirect_to list_path
    end
    
    def show
        @brother = Brother.find(params[:id])
    end
    
    def list
        @brothers = Brother.all
    end
    
    def admin 
        @brothers = Brother.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/brothers/admin.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
<!--    <link rel="stylesheet" href="css/style.css">-->
    <title>Admin Login</title>
</head>

<body>

    <h1>Admin Login</h1>

    <form action="" method="post">
        <label for="username">Username</label>
        <input type="text" id="username" name="username" required> <br>

        <label for="password">Password</label>
        <input type="text" id="password" name="password" required> <br>
        
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        
        <%= submit_tag "Submit" %>
    </form>

    <!--Links-->
    <%=  link_to 'Home', home_path %>
</body>

</html>

app/views/brothers/index.html.erb
<!--<h1>Phi Sigma Pi - List of Brothers</h1>-->

<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>PSP GM Attendance</title>
<!--    <link rel="stylesheet" href="css/style.css">-->
</head>

<body>

    <header>
        <div class="wrapper">
            <div id="logo">
                <h1>Phi Sigma Pi - UC Davis</h1>
                <h2>General Meeting Attendance Tracker</h2>
            </div>

        </div>
        <!--.wrapper-->
    </header>

    <div id="links">
        <%= link_to 'Admin Login', admin_path %>
<!--        <a href="contact.html">GM Minutes</a>-->
    </div>


    <section id="form">
        <!-- Contact Form -->
<!--        <form action="#" method="post">-->
<!--        <form action="<%= brothers_path %>" method="POST">-->
            <%= form_tag brothers_path do %>
            
            <label for="first_name">First Name</label>
            <input type="text" id="first_name" name="brother[first_name]" placeholder="ex: Melissa" size="12" required> <br>

            <label for="last_name">Last Name</label>
            <input type="text" id="last_name" name="brother[last_name]" placeholder="ex: Sheehan" size="12" required> <br>

            <div id="on_time">
                <input type="radio" name="brother[on_time]" value="true">On time<br>
                <input type="radio" name="brother[on_time]" value="false">Late<br>
                <!--  <input type="hidden" name="arrival" value="absent">Absent-->
           </div>

            <label for="email">Email</label>
            <input type="email" id="email" name="brother[email]" placeholder="incredibles@ucdavis.edu" size="22" required> (used to send you a confirmation email)<br>

            <label for="code">Code</label>
            <input type="code" id="code" name="brother[code]" placeholder="123abc" size="8" required> <br>
            
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            
             <%= submit_tag "Submit" %>
<!--            <input id="submitBtn" type="submit" value="send">-->
    <% end %>
<!--        </form>-->

        
<% #= params.inspect %>
   
   
    </section>

    <section id="location">
        <h5>Location: </h5>
         Map 
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3120.6713836706017!2d-121.75359848469128!3d38.54134262545785!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80852908d0ed9e59%3A0x24a87d477f7be660!2sWellman+Hall%2C+Davis%2C+CA+95616!5e0!3m2!1sen!2sus!4v1502829543935" width="425" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
    </section>

    <!-- links -->
    <div id="social">
        <a href="https://www.instagram.com/psp_ucdavis/">Instagram</a>
        <a href="https://www.facebook.com/PhiSigmaPiatUCD/?fref=ts">Facebook</a>
        <a href="http://www.phisigmapidavis.com/">Website</a>
    </div>

    <footer>
        &copy; Phi Sigma Pi Zeta Upsilon
    </footer>
</body>

</html>

app/views/brothers/list.html.erb
<h2>List of Brothers</h2>

<h3>Present</h3>
<ol>
<% present_count = 0 %>
<% late_count = 0 %>

<% @brothers.each do |brother| %>
    <li><div><%= link_to brother.to_s, brother_path(brother) %>
    <% if brother.on_time == false %>
        late
        <% late_count += 1 %>
    <% end %>
    <% present_count += 1 %>
    </div>
    
    </li>
    <% end %>
    <h4>Count: <%= present_count%> </h4>
    <h4>Late Count: <%= late_count%> </h4>
</ol>

<h3>Absent</h3>

app/views/brothers/show.html.erb
<h2><%= @brother.to_s %></h2>

<h4>On time: 
    <% if @brother.on_time == true %>
        yes
    <% else %>
        no
    <% end %>
</h4>


<h4>Email: <%= @brother.email %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Attendance</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>